import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs';
const $=s=>document.querySelector(s),q=new URLSearchParams(location.search),url=q.get('pdf'),name=q.get('title')||'Book',key='pdfbooks:'+url;
let pdf,texts=[],pageNo=1,playing=false,zoom=1.5,visited=new Set();
$('#title').textContent=name;$('#bookTitle').textContent=name;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(key,JSON.stringify({page:pageNo,visited:[...visited]}))}
function show(n,scroll=true){pageNo=Math.max(1,Math.min(pdf.numPages,n));visited.add(pageNo);save();$('#pageInfo').textContent=`Page ${pageNo} / ${pdf.numPages}`;$('#bar').style.width=`${pageNo/pdf.numPages*100}%`;$('#percent').textContent=`${Math.round(pageNo/pdf.numPages*100)}%`;$('#readPages').textContent=visited.size;$('#pageInput').value=pageNo;$('#transcript').textContent=texts[pageNo-1]||'No selectable text.';document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',+x.dataset.page===pageNo));if(scroll)document.querySelector(`canvas[data-page="${pageNo}"]`)?.scrollIntoView({behavior:'smooth',block:'start'})}
function stop(){playing=false;speechSynthesis.cancel();$('#status').textContent='AI Read stopped.'}
function speak(){if(!playing)return;let t=texts[pageNo-1];if(!t){next();return}let u=new SpeechSynthesisUtterance(t);u.rate=+$('#speed').value;u.onend=()=>{if(playing&&pageNo<pdf.numPages){show(pageNo+1);speak()}else{playing=false;$('#status').textContent='Finished reading.'}};speechSynthesis.cancel();speechSynthesis.speak(u);$('#status').textContent=`Reading page ${pageNo}…`}
function next(){if(pageNo<pdf.numPages)show(pageNo+1)} function prev(){if(pageNo>1)show(pageNo-1)}
function chapters(){let h=[];texts.forEach((t,i)=>{for(let line of t.split(/\n|(?<=[.!?])\s+/).slice(0,12).map(x=>x.trim()))if(/^(अध्याय|परिच्छेद|भाग|chapter|part|prologue|epilogue)\b/i.test(line)){h.push({page:i+1,text:line});break}});let u=[];h.forEach(x=>{if(!u.some(y=>y.page===x.page))u.push(x)});$('#toc').innerHTML=u.length?u.map(x=>`<button data-page="${x.page}">p.${x.page} — ${esc(x.text)}</button>`).join(''):'<span class="status">No obvious chapter headings.</span>';document.querySelectorAll('#toc [data-page]').forEach(b=>b.onclick=()=>show(+b.dataset.page))}
function search(){let term=$('#searchInput').value.trim().toLowerCase();if(!term){$('#results').innerHTML='';return}let r=[];texts.forEach((t,i)=>{let at=t.toLowerCase().indexOf(term);if(at>=0)r.push({page:i+1,s:t.slice(Math.max(0,at-50),at+term.length+90)})});$('#results').innerHTML=r.length?r.slice(0,80).map(x=>`<button data-page="${x.page}">p.${x.page} — ${esc(x.s)}</button>`).join(''):'<span class="status">No results.</span>';document.querySelectorAll('#results [data-page]').forEach(b=>b.onclick=()=>show(+b.dataset.page))}
function zoomSet(){document.querySelectorAll('#pages canvas').forEach(c=>c.style.width=`${zoom/1.5*100}%`)}
$('#play').onclick=()=>{playing=true;speak()};$('#stop').onclick=stop;$('#next').onclick=()=>{stop();next()};$('#prev').onclick=()=>{stop();prev()};$('#go').onclick=()=>{stop();show(+$('pageInput').value||1)};$('#pageInput').onkeydown=e=>e.key==='Enter'&&$('#go').click();$('#bookmark').onclick=()=>{localStorage.setItem(key+':bookmark',pageNo);$('#saved').textContent=`Saved page ${pageNo}`};$('#resume').onclick=()=>show(+(localStorage.getItem(key+':bookmark')||1));$('#focus').onclick=()=>document.body.classList.toggle('focus');$('#fullscreen').onclick=()=>document.documentElement.requestFullscreen?.();$('#zoomIn').onclick=()=>{zoom=Math.min(2.6,zoom+.15);zoomSet()};$('#zoomOut').onclick=()=>{zoom=Math.max(.7,zoom-.15);zoomSet()};$('#double').onclick=()=>{$('#pages').classList.toggle('double');$('#double').classList.toggle('active')};$('#themeDark').onclick=()=>document.body.classList.remove('theme-sepia','theme-paper');$('#themeSepia').onclick=()=>document.body.classList.add('theme-sepia');$('#themePaper').onclick=()=>document.body.classList.add('theme-paper');$('#searchBtn').onclick=search;$('#searchInput').onkeydown=e=>e.key==='Enter'&&search();$('#offline').onclick=async()=>{try{await (await caches.open('laxman-pdf-books-pdfs-v1')).add(url);$('#status').textContent='PDF saved for offline reading.'}catch(e){$('#status').textContent='Offline save failed.'}};document.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(e.key==='ArrowRight')next();if(e.key==='ArrowLeft')prev();if(e.key==='f')$('#focus').click();if(e.key==='+'||e.key==='=')$('#zoomIn').click();if(e.key==='-')$('#zoomOut').click();if(e.key===' ')e.preventDefault(),playing?stop():$('#play').click()});
async function load(){pdf=await pdfjsLib.getDocument(url).promise;for(let i=1;i<=pdf.numPages;i++){let p=await pdf.getPage(i),v=p.getViewport({scale:zoom}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;c.dataset.page=i;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;$('#pages').append(c);let tc=await p.getTextContent();texts[i-1]=tc.items.map(x=>x.str).join(' ').replace(/\s+/g,' ').trim()}chapters();let s=JSON.parse(localStorage.getItem(key)||'null'),b=+(localStorage.getItem(key+':bookmark')||0);visited=new Set(s?.visited||[]);$('#saved').textContent=b?`Saved page ${b}`:'No saved page yet.';show(s?.page||b||1,false)}
load().catch(e=>{$('#status').textContent='Could not open this PDF.';console.error(e)});